---
# yaml-language-server: $schema=https://kubernetes-schemas.x00.sh/external-secrets.io/clustersecretstore_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gpc-sm
  namespace: kube-system
spec:
  provider:
    gcpsm:
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcpsm-secret
            key: secret-access-credentials
            namespace: kube-system
      projectID: k8s-prod-397910
