---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-schemas-gatus-ep
  namespace: shared
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: kubernetes-schemas
        group: external
        url: https://kubernetes-schemas.x00.sh
        interval: 1m
        client:
          dns-resolver: tcp://1.1.1.1:53
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: pushover
