apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:Y2sz+6E=,iv:KLW1sa+wK7gz8qSB6O0bntf2CWI3ELVDMenU5iZ+Nlw=,tag:IxDU1U3BOuKexQjrFkst+g==,type:str]
    admin-password: ENC[AES256_GCM,data:5nGoUKkBfjHe8EjQgawiiGn7TKRqJJxr,iv:YmlgfcM9wP8JYBVhZQTNn4gQBS3BoDUWxK2OSMqBntg=,tag:q8KJNoCnNflUWJOa8ZtBFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a6lkd7nhvzk877nwg79uzeagu45f5dkr6d3ls5x0qy589wqj8qtq27tsn3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQWM2L3piZFZxRDRMRi9y
            djhKN29iSTc0Y3FpaHV3cUFHTFJ2TzFYUWljCmtoVzBDTTV3a1lpdlQxMFJQdVJi
            MjBqZ0M1a05sc056azVESHFxbkRMUEEKLS0tIEg2Nm1Wc1c4T3RlWFhJOWpVNlE2
            QUlXeGdZTDI0c3lBNWY2VHoxYUZaRDQKr3PdlIu2WOQ7F5SWCd4dqXiEZ+vjBWb4
            YhGUV7gxcVKg0plt+CjOBogudif8Ms43bNeeFiunNl9GrwARurdL9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-18T09:53:07Z"
    mac: ENC[AES256_GCM,data:njDAwUiwdcUaGY98cCpEeRJR7rsJwdZR8RZRjFWqPpMwovcWNs92ujoP2VRLVUY8URUqQp01JTqDYt4ZJkD4io+S0OnpdGwksB3KfIkslNqfFFaASVIvUSZ6Glxs4XuEj4QAPRbQrtcosCyqH2y7dbIo2/VkWcSWGx1sngohgS0=,iv:Q78iQynb+tZoZVZgRODbkp0wRrEPd6BVFUuoEqhcHLY=,tag:IQVnCuoFUKfB7ONhGH8kyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
