---
# yaml-language-server: $schema=https://kubernetes-schemas.x00.sh/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-theme-park
  namespace: flux-system
spec:
  path: ./kubernetes/apps/shared/theme-park/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
