---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8sgpt
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: k8sgpt/k8sgpt-operator
      version: 0.0.21
      sourceRef:
        kind: HelmRepository
        name: k8sgpt
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
