apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:emeLAVi1,iv:zINI8KLdIC66rejEvvz1ueSuIoDfnpH9q9wIIViBCHo=,tag:Efj1Z3G1jhWKtxrkG59+yg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:kSJtNNaxJNDTBh3I,iv:1V1Qd8nW0St4McxWEMVtBvHweN2thg2FXggWE5tLLcM=,tag:ss5zMLoR/h4OTa6gTXTB1g==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:5aPdA+DgTEdD+mYuMYKK2zQ9YUtrTjB6B3A9h9jVc81QuQD2,iv:5O+sxLOrbDU5J2XoEtFiXwhbaebBvjkSwuoSQgx5czQ=,tag:kkCn+rOvt6FxL0hsk/T3/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a6lkd7nhvzk877nwg79uzeagu45f5dkr6d3ls5x0qy589wqj8qtq27tsn3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlV3grN0I2Ujg5T2hscEJW
            Q0VCSmY3a2xzck1nVTdyK2YwVDQxL3hINXpRCmVjUk9ZSUdldlo4QXNaMkNBZW1s
            cmtIdlZNNVpMcFhyYXRudEpMWm8rRGcKLS0tIGVyck9ubDZVN3hKejZYUnNaRjJv
            Q1MxY1FaU3hHY3dZNzVXVjFxR25Cbk0K4t28dQobRMwSTBACEAYQGt8u9UXqa1jg
            bgcAbORAuhE2aGKReia9UcrjOFW5XSF10rmJPcf/LKzXwCFPM9fJMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-18T09:53:06Z"
    mac: ENC[AES256_GCM,data:j3wmt41671eoeJUDbfJndg6t5M5E2XkYN+FnUjhiz1uSm8r05DD1nFdWbdK0JPl+xboyHa7RiW5kmbWFpzl9tGG8svjaejt7FEvSfoAtZSIaX8PqiySGVaJk5sXyBWkCUIa1SEGY0sBL06s7kp69jRrhJBWmPNeLSf3CQgA88jc=,iv:M+suSauHwxicMgZnna6CoS2xMegrB7fWnMItv8weAXk=,tag:kGWQHcwZTSTSeH28BZ2H3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
