---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-synology-csi
  namespace: flux-system
spec:
  path: ./kubernetes/apps/kube-system/synology-csi/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substituteFrom: []
  decryption:
    provider: sops
  dependsOn:
    - name: cluster-apps-snapshot-controller
