apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:LQPgYPDcwpwF7jfsIbYZ6VSkjTzvw0d3uP/LzLjFwFKI5QgE,iv:MKflGceyyfuc+uS2MCeUgrYgqWougcoq8c3B0AsiJcU=,tag:G1v6MrSWvu9nBEpgsvL9Ag==,type:str]
    credentials.json: ENC[AES256_GCM,data:0Sczc5aUPgvSBwES4CvwzUlcc4G9gEjMhPnyClS2X/QdWBGwWLjFUBAaCB/WOe4HUS8tpgoR0663fqY/USItQgPBApnniWARUoHNBHYuwm9gUx6vO2zTj9LCg0eYURLEXbbLIgbCAw1XrfIl1Ury+79jWJo9kmOL0awcGZl6v10k8QssPpWRx+GGnuN2DkNadTkNvgrtfd6xw5LabT0TnGoOEa4CE4Kl0YWhMhJB/Q==,iv:bLVGG8qSzn08iosJS/rS5Uh/AO/Mt50dWUnG/pMKJpc=,tag:oSNsedtSfkpMGHeK5rPhCA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a6lkd7nhvzk877nwg79uzeagu45f5dkr6d3ls5x0qy589wqj8qtq27tsn3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNjQ5RVhaNVJEV21XaU9p
            ditwbFVZUVBkVGFLRkIwRDRySWt1dVRJMkJRClN6eC9OYWJHR2YzOGxOR2l1S0o4
            Q0RsOS8xckZuOWc3ZklQODhkZ1dhaW8KLS0tIFcxcC9YYlRRTHl5aVg2NHlWKzQ5
            cW1ES0w5clgzd09XYUNyZWNTMk4zbUEKACdeSbmy5P3w5214GdbZX0kfJ3APb2eZ
            7DuM13czDXhrrESaXcGpENPrMqOhKx64muaP2XSeE9s0/mqhHvEdiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-18T09:53:07Z"
    mac: ENC[AES256_GCM,data:yVHSXUqGqImkiUSTT+TN0wEfqcNW7xCOzmg4l8CP14dkkb5+AoDKRxCnAXpUZz6Iri2YOczy/1E0JOm6VcOaTM7vAilR7VYApCU6hOefvw6hdKYvEzk6iOARjZLIqR4dEnX8uOYOBmvHddXVqMZJMq8/wDgb87CHSG4LmgLt/9Y=,iv:tg7ixieTm7bQ9LW3UdYcpptgALkw2S1nZ9DKNOPI7/A=,tag:di3rlQ7x5Kgo5b2uELewdQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
