---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: synology-csi
  namespace: storage
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://zebernst.github.io/synology-csi-talos
      chart: synology-csi
      version: 0.9.3
      sourceRef:
        kind: HelmRepository
        name: synology-csi
        namespace: flux-system
      interval: 30m
  values:
    clientInfoSecret:
      create: false
      name: synology-csi-secret
    images:
      attacher:
        image: registry.k8s.io/sig-storage/csi-attacher
        pullPolicy: IfNotPresent
        tag: v4.2.0
      nodeDriverRegistrar:
        image: registry.k8s.io/sig-storage/csi-node-driver-registrar
        pullPolicy: IfNotPresent
        tag: v2.6.3
      plugin:
        image: ghcr.io/zebernst/synology-csi
        pullPolicy: IfNotPresent
        # Defaults to {{ $.Chart.AppVersion }} if empty or not present:
        tag: v1.1.2
      provisioner:
        image: registry.k8s.io/sig-storage/csi-provisioner
        pullPolicy: IfNotPresent
        tag: v3.4.0
      resizer:
        image: registry.k8s.io/sig-storage/csi-resizer
        pullPolicy: IfNotPresent
        tag: v1.7.0
      snapshotter:
        image: registry.k8s.io/sig-storage/csi-snapshotter
        pullPolicy: IfNotPresent
        tag: v6.2.1
    storageClasses:
      synology-iscsi-delete:
        isDefault: false
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        parameters:
          dsm: ${SYNOLOGY_HOST}
          fstype: ext4
          type: thin
          # location: '/volume1'
          protocol: iscsi
      synology-iscsi-retain:
        reclaimPolicy: Retain
        volumeBindingMode: Immediate
        isDefault: true
        parameters:
          dsm: ${SYNOLOGY_HOST}
          fstype: ext4
          type: thin
          # location: '/volume1'
          protocol: iscsi
      synology-media:
        parameters:
          dsm: ${SYNOLOGY_HOST}
          fstype: ext4
          location: '/volume1/media'
          protocol: nfs4
    volumeSnapshotClasses:
      synology-iscsi-delete:
        deletionPolicy: Delete
      synology-iscsi-retain:
        deletionPolicy: Retain
