apiVersion: v1
kind: Secret
metadata:
    name: synology-csi-secret
    namespace: storage
stringData:
    client-info.yml: ENC[AES256_GCM,data:UuCO8slLcjIVx4YvjMsEyXFqmaYGnJvjh2zozVvr+MFHlV9DBjCS6Zm1+8VJ1IxYo4Av5Lv+Ik/GQDppbiolUcncmETfpafLVzs7Kb9YxN7p52a+aGPWNqdd,iv:0AGmWQjKcp3auzcRRF4ZtImWjK/wH3nzahrPh2tlQDo=,tag:6VSeDMXdJS0eBvkn7FOcig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a6lkd7nhvzk877nwg79uzeagu45f5dkr6d3ls5x0qy589wqj8qtq27tsn3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUEpPVmt4RWIzNDFZcGty
            RFdDOTVqUGxFUzJoaDFibnpmUDJFamRXdUVBCmF2K0Z1Yjh4c0lPZlg0NWl0YU5I
            U2hRajdBSU5XQnAvdm5ON2RiY0VWa1UKLS0tIGxwZis4QU9TMWlsVkhSVlQ4Vm4w
            TFdESHk4MmhnemVYTDJtcWVsTUI4d1UK4dNr0GS6SxAcZchR2PJxuNvzVUsfKu++
            X7tMOlXxlTH0Bzx0Ve3pgrd1Pa95EU1hWB0q53Mw+ZRaeeXT5KDlBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-09T13:08:34Z"
    mac: ENC[AES256_GCM,data:X8ON20VUG9Lma/p6two7+c/HzQFN0FhoaNKaXgbrikPhLBuOERoPLQ9IjSx90BuwaQX1UG6W1kgRnfXoPspyESnMoUxQlxtUEfCHE3D2m1GVB8Pw74QY3e5oryYvMkhsfZaHlBZNQbgIy5hsEpiry59s8ePJ1mVlWCbLeBDvHG8=,iv:GLHOCmQwmGa07kGwoxl5WNqtgfPMCBqfiEAqbFpMMsw=,tag:HCvRBCfcC7RTTNFuuPxntA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
