apiVersion: v1
kind: Secret
metadata:
    name: gatus
    namespace: monitoring
stringData:
    SLACK_WEBHOOK_URL: ENC[AES256_GCM,data:lLwonXE3EkCTgjbK7g1696ynDLrhpY+b9Td/xfGDPSvs33XvOvL8kyFd73v8ns0G6cU3a2DD632h5/HtTAvv4jvkG6xkormCjUCN2Gdq7UjD,iv:mIFkYLUmdBYxfd/Nxja4Juw7sp4g0LEAEldOGSHb4js=,tag:5SsZFSUzJN9IX/Jm9zFb8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a6lkd7nhvzk877nwg79uzeagu45f5dkr6d3ls5x0qy589wqj8qtq27tsn3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHS0dpSy9SRzVNN3VoY0tH
            UUVOM2pER0Y1N3d4UTFoSDlDYVJQVDJsTXlzClRvdW95U2NzRHFSSTdCUFJKa0Fv
            SmtXMUdoUFZrZm01VmhuejdjM2JLZjQKLS0tIDZNTElubEJQZis0b3lDdXY3Sm9R
            bXFCVGZiNnorZnV1cllPcm9DTGdRMEUK6VT3oDfJGhsTUHRQ/eGnE2ubzhkaEa2v
            FtA3WSy5DFJYBT4KsZkatGpctFkion69Y/wjWam+LsMK5qK1mb9Z9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-08T14:31:26Z"
    mac: ENC[AES256_GCM,data:D6b8PfSQRieq0B6nUKruXy0K8m2Pbt96lVhN5WaNK3fubU7ZSYf1VDz8JWcl7XqigYo7tN40eiQ5NqpNYQNznUJ2uTCVcn3oR3RvZ0h961pl3/p4veTgndxay2HOmNuy6AMkUG0uVHmI7xhKBb/p/E2zkXSRGMIezzN2CapPYgI=,iv:EHCVOuV6UpNfladPS06C1/dUES17QvwdB4gCCJvrMCY=,tag:iMwAtXyJSt/1TIYKuXqXSA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
